name: Deploy to Azure App Service

on:
  workflow_dispatch:  # 手動実行のみ

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-002-gen10-step3-2-py-oshima8'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A0424BCDDFEA4094B26EC23E8E8C19F0 }}
        package: .